# -*- coding: utf-8 -*-
"""Proyek Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ug4Ox4qIFDSo1koFA0XiNJE-ce12rECy

# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** Novi Ken Sydney
- **Email:** m277b4kx3401@bangkit.academy
- **ID Dicoding:** novi_ken_sydney_m277b4kx3401_Kq1P

## Menentukan Pertanyaan Bisnis

- Bagaimana pengaruh cuaca terhadap penggunaan sepeda?
- Bagaimana pola penggunaan sepeda pada hari kerja dan akhir pekan?

## Import Semua Packages/Library yang Digunakan
"""

pip install streamlit

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
from datetime import datetime

"""## Data Wrangling

### Gathering Data
"""

# Load dataset
df = pd.read_csv('/content/day.csv')

# Lihat 5 data teratas
df.head()

"""**Insight:**

Dataset terdiri dari beberapa fitur terkait:

1.   cuaca (temp, atemp, hum, windspeed), waktu (dteday, season, weekday)
2.   jumlah pengguna sepeda (cnt, casual, registered)

### Assessing Data
"""

# Menampilkan informasi tentang tipe data dan missing values
df.info()

# Statistik deskriptif
df.describe()

"""**Insight:**
- Tidak ada missing value, semua data terisi penuh.
- Kolom dteday harus diubah menjadi tipe datetime.

### Cleaning Data
"""

# Mengubah kolom 'dteday' menjadi datetime
df['dteday'] = pd.to_datetime(df['dteday'])

# Cek data duplikat
df.duplicated().sum()

"""**Insight:**
- Data sudah bersih dan tidak ada duplikat.

## Exploratory Data Analysis (EDA)

### Explore Pengaruh Cuaca terhadap Penggunaan Sepeda
"""

# Boxplot penggunaan sepeda berdasarkan cuaca
sns.boxplot(x='weathersit', y='cnt', data=df)
plt.title('Pengaruh Cuaca terhadap Penggunaan Sepeda')
plt.show()

"""**Insight:**
- Cuaca cerah dan berawan lebih mendorong penggunaan sepeda, sementara cuaca buruk mengurangi jumlah pengguna.

### Explore Pola Penggunaan Sepeda pada Hari Kerja vs Akhir Pekan
"""

# Barplot penggunaan sepeda berdasarkan hari kerja vs akhir pekan
sns.barplot(x='workingday', y='cnt', data=df)
plt.title('Penggunaan Sepeda pada Hari Kerja vs Akhir Pekan')
plt.show()

"""## Visualization & Explanatory Analysis

### Pertanyaan 1:

Bagaimana pengaruh cuaca terhadap penggunaan sepeda?
"""

# Visualisasi pengaruh cuaca
sns.boxplot(x='weathersit', y='cnt', data=df)
plt.title('Pengaruh Cuaca terhadap Penggunaan Sepeda')
plt.show()

"""### Pertanyaan 2:

Bagaimana pola penggunaan sepeda pada hari kerja vs akhir pekan?
"""

# Visualisasi pola penggunaan sepeda pada hari kerja dan akhir pekan
sns.barplot(x='workingday', y='cnt', data=df)
plt.title('Penggunaan Sepeda pada Hari Kerja vs Akhir Pekan')
plt.show()

"""**Insight:**
- Pengguna cenderung lebih banyak menggunakan sepeda ketika cuaca baik.
- Penggunaan sepeda lebih tinggi di hari kerja, yang mungkin menunjukkan sepeda digunakan untuk perjalanan menuju tempat kerja atau sekolah.

## Analisis Lanjutan (Opsional)

RFM Analysis
"""

# Mengonversi dteday menjadi format datetime
df['dteday'] = pd.to_datetime(df['dteday'])

# Menghitung Recency, Frequency, dan Monetary
df['recency'] = (df['dteday'].max() - df['dteday']).dt.days
df['monetary'] = df['cnt']

# Frequency dihitung per hari
frequency = df.groupby('dteday').agg({'cnt': 'sum'}).reset_index()

# Segmentasi RFM
df['R_score'] = pd.qcut(df['recency'], 4, labels=[1, 2, 3, 4])
df['F_score'] = pd.qcut(df['cnt'], 4, labels=[4, 3, 2, 1])
df['M_score'] = pd.qcut(df['monetary'], 4, labels=[1, 2, 3, 4])
df['RFM_score'] = df['R_score'].astype(str) + df['F_score'].astype(str) + df['M_score'].astype(str)

# Visualisasi RFM Score
sns.countplot(x='RFM_score', data=df)
plt.title('Distribusi RFM Score')
plt.show()

"""Clustering (Manual Grouping/Binning)"""

# Membuat bins berdasarkan jumlah penggunaan sepeda
bins = [0, 100, 300, df['cnt'].max()]
labels = ['Rendah', 'Sedang', 'Tinggi']
df['usage_category'] = pd.cut(df['cnt'], bins=bins, labels=labels)

# Visualisasi distribusi penggunaan sepeda berdasarkan kategori
sns.countplot(x='usage_category', data=df)
plt.title('Distribusi Penggunaan Sepeda Berdasarkan Kategori')
plt.show()

"""## Conclusion

- Cuaca sangat mempengaruhi penggunaan sepeda, di mana cuaca cerah mendorong lebih banyak orang menggunakan sepeda.

- Penggunaan sepeda lebih tinggi pada hari kerja, menunjukkan kemungkinan besar digunakan untuk perjalanan rutin seperti ke kantor atau sekolah.
"""